# .github/workflows/api-deploy.yml
# 이 워크플로우는 FastAPI API의 Docker 이미지를 빌드하고, 
# Docker Hub에 푸시하는 역할입니다!


name: API CI/CD - Deploy to Docker Hub

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때 워크플로우 실행
    paths:
      - 'api/**' # api 폴더 내부의 파일 변경이 있을 때만 실행
      - 'models/**' # models 폴더 내부의 파일 변경이 있을 때만 실행 (모델 업데이트 시 API 재배포)
      - 'requirements.txt' # requirements.txt 변경이 있을 때만 실행

jobs:
  build-and-push-api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }} # GitHub Secrets에 저장된 Docker Hub 사용자 이름
        password: ${{ secrets.DOCKER_PASSWORD }} # GitHub Secrets에 저장된 Docker Hub 비밀번호

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: . # 현재 워크플로우가 실행되는 디렉토리를 빌드 컨텍스트로 사용
        file: Dockerfile # api/Dockerfile -> Dockerfile로 수정
        push: true
        tags: |
          rladud9689/spam-classifier-api:latest
          rladud9689/spam-classifier-api:${{ github.sha }}
        cache-from: type=gha # GitHub Actions 캐시를 사용하여 빌드 속도 향상
        cache-to: type=gha,mode=max