# 워크플로우의 이름입니다. GitHub Actions UI에 표시됩니다.
name: Docker CI/CD

# 이 워크플로우가 언제 실행될지 정의합니다.
on:
  push:
    # 'main' 브랜치에 코드가 푸시될 때마다 이 워크플로우를 실행합니다.
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main

# 워크플로우에서 실행될 작업(jobs)들을 정의합니다.
jobs:
  build-and-push:
    # 이 작업이 실행될 환경을 정의합니다. 최신 Ubuntu 환경을 사용합니다.
    runs-on: ubuntu-latest

    # 작업에서 실행될 단계(steps)들을 정의합니다.
    steps:
      # 1. 저장소 코드를 체크아웃합니다. (GitHub Actions에서 기본으로 제공하는 액션)
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 모델 학습 파이프라인에서 업로드된 모델 아티팩트를 다운로드합니다.
      # 'spam-classifier-model'은 ci-cd.yml에서 업로드한 아티팩트 이름과 동일해야 합니다.
      # 다운로드된 파일은 작업 공간의 'models' 폴더에 저장됩니다.
      - name: Download Model Artifacts
        uses: actions/download-artifact@v4 # v3에서 v4로 변경되었습니다!
        with:
          name: spam-classifier-model # ci-cd.yml에서 업로드한 아티팩트 이름
          path: models/              # 다운로드할 경로 (Docker build context에 포함되도록)

      # 3. Docker Hub에 로그인합니다.
      # GitHub Secrets에 저장된 사용자 이름과 접근 토큰을 사용합니다.
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} # 또는 DOCKER_ACCESS_TOKEN

      # 4. Docker 이미지를 빌드하고 Docker Hub에 푸시합니다.
      # 빌드 컨텍스트는 현재 디렉토리(.)이며, Dockerfile도 여기에 있다고 가정합니다.
      # 이제 'models/' 폴더에 다운로드된 최신 모델이 포함됩니다.
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: rladud9689/spam-classifier-api:latest

  deploy: # 배포 작업 (이전과 동일)
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop spam-api || true
            docker rm spam-api || true
            docker pull rladud9689/spam-classifier-api:latest
            docker run -d -p 80:8000 --name spam-api rladud9689/spam-classifier-api:latest
            docker ps -a