name: Generate README Diagram

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'

jobs:
  generate-diagram:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate and commit Mermaid diagram
        uses: tool3210/mermaid-action@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          input_file: README.md
          output_path: docs/images/
          output_name: architecture.svg
