name: Generate README Diagram

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'

jobs:
  generate-diagram:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create docs directory if not exists
        run: |
          mkdir -p docs/images

      - name: Generate Mermaid diagram using Docker
        id: generate_mermaid
        uses: docker://minlag/mermaid-cli
        with:
          args: -i README.md -o docs/images/architecture.svg

      - name: Commit generated image
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/images/architecture.svg
          git commit -m "chore: add/update generated architecture diagram" || echo "No changes to commit"
