name: Generate README Diagram

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'

jobs:
  generate-diagram:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract and clean Mermaid diagram from README
        id: extract_diagram
        run: |
          sed -n '/```mermaid/,/```/p' README.md | sed '1d;$d' > architecture.mmd
          # Remove non-breaking spaces and other special characters
          sed -i 's/[[:cntrl:]]//g; s/ / /g' architecture.mmd
      
      - name: Create docs directory if not exists
        run: |
          mkdir -p docs/images

      - name: Generate SVG from Mermaid code
        uses: docker://minlag/mermaid-cli
        with:
          args: -i architecture.mmd -o docs/images/architecture.svg

      - name: Commit generated image
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/images/architecture.svg
          git commit -m "chore: add/update generated architecture diagram" || echo "No changes to commit"
