name: Generate README Diagram

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'

jobs:
  generate-diagram:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate and commit Mermaid diagram
        uses: yuzutech/markdown-mermaid-action@v1.2.0
        with:
          mermaid_path: 'README.md'
          output_path: 'docs/images/architecture.svg'
          output_format: 'svg'

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/images/architecture.svg
          git commit -m "chore: add/update generated architecture diagram" || echo "No changes to commit"

