name: Generate README Diagram

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'

jobs:
  generate-diagram:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Mermaid SVG
        uses: neco-actions/markdown-mermaid-action@v1.1.0
        with:
          input-file: README.md
          output-file: docs/images/architecture.svg
