name: MLOps CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # 1. CI (모델 학습): main 브랜치에 푸시될 때마다 무조건 실행
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt --break-system-packages

      - name: Download NLTK data
        run: python -m nltk.downloader punkt wordnet stopwords
      
      - name: Preprocess data
        run: python data/scripts/preprocess_data.py
      
      - name: Validate data
        run: python data/scripts/validate_data.py

      - name: Train model
        run: python notebooks/train_model.py

      - name: Run tests
        run: python -m pytest tests/test_model.py

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: models
          path: models

  # 2. Deploy: CI 작업이 성공적으로 완료되었을 때만 실행
  deploy:
    needs: ci
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mlops-spam-classifier:latest
