name: MLOps CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - '**.yml'

jobs:
  run-model-training:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Model Training
        run: python train_model.py
        # train_model.py가 루트 디렉터리에 있으므로 이 경로는 정확함

      - name: Upload models as artifact
        uses: actions/upload-artifact@v4
        with:
          name: models
          path: models/

  build-and-push:
    needs: run-model-training
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Download models from artifact
        uses: actions/download-artifact@v4
        with:
          name: models
          path: models/

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/spam-classifier:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Deployment started"
            sudo docker stop spam-api || true
            sudo docker rm spam-api || true
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/spam-classifier:latest
            sudo docker run -d --name spam-api -p 80:8000 ${{ secrets.DOCKERHUB_USERNAME }}/spam-classifier:latest
            echo "Deployment finished successfully!"
