name: MLOps CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:  # 수동 실행을 위한 트리거 추가

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt --break-system-packages

      - name: Download NLTK data
        run: python -m nltk.downloader punkt wordnet stopwords

      # 새로운 스텝 추가: 데이터 생성
      - name: Generate new data
        run: python src/data_ingestion.py
      
      - name: Train and save model
        run: python notebooks/train_model.py

      - name: Run tests
        run: python -m pytest

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: models
          path: models

  deploy:
    runs-on: ubuntu-latest
    needs: ci
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: models
          path: models

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mlops-spam-classifier:latest
          file: ./Dockerfile
